In [53]:
import numpy as np
import timeit

m,n=20,10
A=np.random.rand(m,n)
k=np.random.rand(n)
p=np.zeros(m)

# Approach 1: Using a for loop
def Multiplication_with_for_loop(A,k,p):
  for i in range(n):
    p+=A[:,i]*k[i]
  return p

# Approach 2: Using the function
def Multiplication_with_function(A,k):
  return np.dot(A, k)

print(Multiplication_with_for_loop(A,k,p))
print(Multiplication_with_function(A,k))
print()

print("result np.allclose " ,np.allclose(p,np.dot(A, k)))

# Measure the execution time for each approach
time_for_loop = timeit.timeit(lambda: Multiplication_with_for_loop(A,k,p), number=1000)
time_for_function = timeit.timeit(lambda: np.dot(A, k), number=1000)

print("Execution time using for loop:", time_for_loop)
print("Execution time using function:", time_for_function)

[2.87181458 3.26759452 3.26177683 2.63604559 3.11722788 2.43199331
 1.99469906 3.3805834  3.21886788 2.15668689 2.25177639 3.24627812
 3.54384768 2.18538437 2.18151831 2.68017798 2.85441108 3.91308034
 3.08615813 2.28383416]
[2.87181458 3.26759452 3.26177683 2.63604559 3.11722788 2.43199331
 1.99469906 3.3805834  3.21886788 2.15668689 2.25177639 3.24627812
 3.54384768 2.18538437 2.18151831 2.68017798 2.85441108 3.91308034
 3.08615813 2.28383416]

result np.allclose  True
Execution time using for loop: 0.02086581399998977
Execution time using function: 0.0010387399997853208


In [ ]:
import numpy as np

# Define the matrix A and vector b
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
b = np.array([3, 7, 11])

# Compute the SVD of A
U, Sigma, Vt = np.linalg.svd(A)

# Calculate the pseudo-inverse of A
Sigma_pseudo_inv = np.zeros((A.shape[1], A.shape[0]))
Sigma_pseudo_inv[:A.shape[1], :A.shape[1]] = np.diag(1/Sigma)

A_pseudo_inv = Vt.T.dot(Sigma_pseudo_inv).dot(U.T)

# Compute the least squares solution
x = A_pseudo_inv.dot(b)

print("Least squares solution:")
print(x)

Least squares solution:
[1. 1.]


In [47]:
import numpy as np

def is_nonsingular(matrix):
    det = np.linalg.det(matrix)
    if det != 0:
        return True
    else:
        return False

# Example matrix
matrix_A = np.array([[1, 2,3],
                     [0, 4,1],
                     [0, 0,1]])

print("matrix A =", "\n" ,matrix_A)

matrix_B = np.array([[1, 2,3],
                     [0, 4,1],
                     [0, 0,0]])

print("\n matrix B =","\n" ,matrix_B)

if is_nonsingular(matrix_A):
    print("\nThe matrix_A is nonsingular.")
else:
    print("The matrix_A is singular.")

if is_nonsingular(matrix_B):
    print(" The matrix_B is nonsingular.")
else:
    print("The matrix_B is singular.")


matrix A = 
 [[1 2 3]
 [0 4 1]
 [0 0 1]]

 matrix B = 
 [[1 2 3]
 [0 4 1]
 [0 0 0]]

The matrix_A is nonsingular.
The matrix_B is singular.
